openapi: 3.1.0 #wishful thinking that our spec is 3.1 at the moment

info:
  title: Signable API  
  description: The Signable API provides secure and efficient access to Signable's electronic 
    signature platform. With this RESTful API, you can send documents for signature, 
    manage templates, track envelope status, and automate your document workflows 
    from within your own applications. Please see https://developer.signable.co.uk/ 
    for more details.  
  version: 1.0.0  
  contact:
    name: Signable
    email: help@signable.co.uk  
  termsOfService: https://www.signable.co.uk/terms-conditions/  
  license:
    name: Proprietary
    url: https://www.signable.co.uk/terms-conditions/
servers:
  - url: https://api.signable.co.uk/v1
    description: Production server
security:
  - basicAuth: []
x-tagsGroups:
  - name: Branding
    tags:
      - Branding
  - name: Settings
    tags:
      - Settings
  - name: Webhooks
    tags:
      - Webhooks
      
webhooks:
  send-envelope:
    post:
      summary: Notification when an envelope is successfully sent
      description: >
        This webhook is triggered after an envelope has been successfully processed and sent.
        It delivers information about the envelope, the recipient, any additional metadata,
        and a download URL. Payload is sent as application/x-www-form-urlencoded.
      operationId: receiveSendEnvelopeWebhook
      tags:
        - Webhooks
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                envelope_fingerprint:
                  type: string
                  description: A string representing the envelope that was sent
                envelope_documents:
                  type: string
                  description: A JSON string representing the documents within the envelope
                envelope_download:
                  type: string
                  format: uri
                  description: A URL to download the envelope contents
                contact_id:
                  type: integer
                  description: The ID of the contact the envelope was sent to
                contact_name:
                  type: string
                  description: The name of the contact the envelope was sent to
                contact_email:
                  type: string
                  format: email
                  description: The email address of the contact the envelope was sent to
                action:
                  type: string
                  enum: [send-envelope]
                  default: send-envelope
                  description: The action taken. Defaults to `send-envelope`.
                action_date:
                  type: string
                  format: date-time
                  description: The UTC timestamp of when the action occurred
                envelope_meta:
                  type: string
                  description: A JSON string of any meta information added when sending the envelope
                envelope_signing_embed:
                  type: string
                  description: An iframe URL for embedded signing, if enabled
              required:
                - envelope_fingerprint
                - envelope_documents
                - envelope_download
                - contact_id
                - contact_name
                - contact_email
                - action
                - action_date
            example:
              envelope_fingerprint: "3945323c87601815b6673a62d9eb17d9"
              envelope_documents: '[{"document_title":"Untitled document","document_fingerprint":"5e8df3ca4ee32668b180326ed63bec81","document_pdf":"https://api.signableapi.com/shareable/document?t=2e4f1bbf-e786-42af-aae8-16b8j6ccb527","document_download":"https://api.signableapi.com/shareable/document?t=2e4f1bbf-e786-42af-aae8-16b8j6ccb527"}]'
              envelope_download: "https://api.signableapi.com/shareable/envelope?t=cf4dnn6dd-8400-4c29-83fb-befcb34c280a"
              envelope_signing_embed: '<iframe src="https://sign.signable.app/#2KnUUnVQTxtkpV8rmWqem9qXpvaTU2hYLHHyQD7WtdQ" width="100%" height="95%" frameborder="0" style="border: 0; overflow: hidden"></iframe>'
              contact_id: 14029945
              contact_name: "Andy Jackson"
              contact_email: "andy@wearedomo.com"
              action: "send-envelope"
              action_date: "2025-06-20T15:50:10+00:00"
              envelope_meta: ""  
      responses:
        '200':
          description: Acknowledge receipt

  # need to add all the other webhooks

paths:
  /branding:
    get:
      summary: Get branding settings
      description: >
        Returns your company's current branding settings, including any uploaded logo and primary colour.
        These settings control how Signable emails and signing pages appear to your signers.
      operationId: getBranding
      tags:
        - Branding

      responses:
        "200":
          description: Branding settings returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandingResponse'
              examples:
                default:
                  $ref: '#/components/examples/BrandingResponseExample'

    put:
      summary: Update branding preferences
      description: >
        Update your account's branding settings. This includes the logo and the primary colour used on emails and signing pages.
      operationId: updateBranding
      tags:
        - Branding
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandingPutRequest'
            examples:
                default:
                  $ref: '#/components/examples/BrandingPutRequest'
      responses:
        '200':
          description: Branding updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandingPutResponse'
              examples:
                default:
                  $ref: '#/components/examples/BrandingPutResponse'

  /settings:
    get:
      summary: Get company settings
      description: >
        Your Signable account settings control how documents are delivered, signed, and managed across your team.<br>
        <br>
        This section of the API lets you retrieve and update your company's signing preferences, email notification 
        rules, signature formats, and moreâ€”giving you full control over how your documents behave.<br>
        <br>
        Settings can be accessed via the API or in the Signable web app under 
        Company Settings > [Preferences](https://signable.app/company-settings/preferences).<br>
        <br>
      operationId: listSettings
      tags:
        - Settings

      responses:
        "200":
          description: Company settings returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsResponse'
              examples:
                default:
                  $ref: '#/components/examples/SettingsResponseExample'

    put:
      summary: Update company settings
      operationId: updateSettings
      tags:
        - Settings
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSettingsRequest'
            examples:
              default:
                $ref: '#/components/examples/SettingsPutRequestExample'

      responses:
        "200":
          description: Settings updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSettingsResponse'
              examples:
                updated:
                  $ref: '#/components/examples/SettingsPutResponseExample'      

  /webhooks:
    get:
      summary: Get all registered webhooks
      description: >
        Retrieves a paginated list of all webhooks currently registered to receive event notifications.
        Supports offset and limit for pagination. Webhooks include metadata about creation, update, and suspension state.
      operationId: listWebhooks
      tags:
        - Webhooks
      parameters:
        - name: offset
          in: query
          required: false
          description: Pagination offset
          schema:
            type: integer
            example: 0

        - name: limit
          in: query
          required: false
          description: Number of webhooks to return
          schema:
            type: integer
            example: 10

      responses:
        "200":
          description: Successfully returned a list of webhooks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookListResponse'
              examples:
                default:
                  $ref: '#/components/examples/WebhookListResponseExample'
                  
    post:
      summary: Create a new webhook
      description: >
        Registers a new webhook that will be triggered when a specific event occurs.
        You must provide a valid `webhook_url` and a supported `webhook_type`. 
        The created webhook will immediately be eligible to receive matching notifications.
      operationId: createWebhook
      tags:
        - Webhooks

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
            examples:
              default:
                $ref: '#/components/examples/WebhookRequestExample'

      responses:
        "200":   #should be a 201!
          description: Webhook successfully created
          headers:
            Location:
              description: The URL of the newly created webhook resource
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookPostResponse'
              examples:
                createdWebhook:
                  $ref: '#/components/examples/WebhookPostResponseExample'

  /webhooks/{webhook_id}:
    get:
      summary: Get a single webhook
      description: >
        Retrieves details of a specific webhook by its unique `webhook_id`. 
        The response includes the current status and metadata of the webhook.
      operationId: getWebhook
      tags:
        - Webhooks

      parameters:
        - name: webhook_id
          in: path
          required: true
          description: The ID of the webhook to retrieve
          schema:
            type: integer
            example: 152691

      responses:
        "200":
          description: Webhook details returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookGetResponse'
              examples:
                default:
                  $ref: '#/components/examples/WebhookGetResponseExample'

    put:
      summary: Update an existing webhook
      description: >
        Updates the webhook identified by `webhook_id`. You may change the `webhook_url` and/or the `webhook_type`.
      operationId: updateWebhook
      tags:
        - Webhooks

      parameters:
        - name: webhook_id
          in: path
          required: true
          description: The ID of the webhook to update
          schema:
            type: integer
            example: 152691

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
            examples:
              default:
                $ref: '#/components/examples/WebhookRequestExample'

      responses:
        "200":
          description: Webhook updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookPutResponse'
              examples:
                updated:
                  $ref: '#/components/examples/WebhookPutResponseExample'

    delete:
      summary: Delete a webhook
      description: >
        Deletes the webhook identified by `webhook_id`. Once removed, the webhook will no longer receive event notifications.
      operationId: deleteWebhook
      tags:
        - Webhooks

      parameters:
        - name: webhook_id
          in: path
          required: true
          description: The ID of the webhook to delete
          schema:
            type: integer
            example: 152691

      responses:
        "200":
          description: Webhook successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookDeleteResponse'
              examples:
                deleted:
                  $ref: '#/components/examples/WebhookDeleteResponseExample'

components:
  schemas:
    BrandingResponse:
      type: object
      required:
        - http
        - branding_logo
        - branding_colour
      properties:
        http:
          type: integer
          description: HTTP status code
          example: 200

        branding_logo:
          type: [string, "null"]
          format: uri
          description: >
            A public URL to your uploaded logo (shown on emails and signing pages).
            Returns `null` if no logo is uploaded.
          example: https://www.signable.co.uk/signable.png

        branding_colour:
          type: string
          description: >
            The primary hex colour used for branding emails and signing pages.
          example: "#0095E6"

    BrandingPutRequest:
      type: object
      properties:
        branding_logo_url:
          type: [string, "null"]
          format: uri
          description: >
            A public URL to your logo. This will be shown on emails and the signing page.
            Set to `null` to remove the current logo.
          example: https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png

        branding_colour:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          description: >
            The hex colour code (e.g. `#0095E6`) used for branded emails and signing pages.
          example: "#558caa"
      required:
        - branding_logo_url
        - branding_colour

    BrandingPutResponse:
      type: object
      required:
        - http
        - message
        - branding_logo
        - branding_colour
      properties:
        http:
          type: integer
          description: HTTP status code
          example: 200

        message:
          type: string
          description: A success message confirming the update
          example: Branding options have been updated.

        branding_logo:
          type: [string, "null"]
          format: uri
          description: >
            The final logo URL now active for your account. Will be `null` if none is set.
          example: https://assets.signable.co.uk/company-logo/213690-1751360856.png

        branding_colour:
          type: string
          description: >
            The hex code now being used for branding emails and signing pages. Will be `null` if none is set.
          example: "#558CAA"

    SettingsFields:
      type: object
      description: Common company settings shared across settings GET and PUT operations.
      properties:
        setting_signature_more_info:
          type: boolean
          description: >
            If enabled, the signature will display the signer name and timestamp under each signature block on the generated Envelope PDF.
          example: true

        setting_signature_format_default:
          type: string
          description: >
            Which signature format is offered by default. Accepted values: `drawn`, `typed`, or `upload`.
          example: typed

        setting_signature_format_accepted:
          type: string
          description: >
            Comma-separated list of signature formats your account accepts. Valid values: `drawn`, `typed`, `upload`.
          example: typed,drawn,upload

        setting_email_pdf_attach:
          type: boolean
          description: >
            If enabled, the document to be signed will be attached as a PDF in emails. 
            If disabled, no PDF will be attached. Recipients can still view the document via a link in the email.
          example: true

        setting_email_envelope_open:
          type: boolean
          description: >
            If enabled, an email notification will be sent when someone opens the envelope.
          example: true

        setting_email_main_email:
          type: boolean
          description: >
            If enabled, notifications (signed, rejected, cancelled) are sent to your companyâ€™s main email address.
          example: true

        setting_email_return_address_user:
          type: boolean
          description: >
            If enabled, the "Return Email" will be set to the user who sent the envelope, rather than the main company email.
            If disabled, the "Return Email" will be set to your main company email address.
            Regardless of this property, emails will always be sent from document@signable.co.uk.
          example: true

        setting_signing_consumer_regulations_act:
          type: boolean
          description: >
            Enables [Consumer Contract Regulations 2013 compliance](http://www.legislation.gov.uk/uksi/2013/3134/pdfs/uksi_20133134_en.pdf) 
            for your account. Only set this to 'Yes' if you believe that you need this enabled. 
            This setting will change some of the terminology on the signing page to become 
            compliant with this Act.
          example: false

        setting_signing_tooltips:
          type: boolean
          deprecated: true
          description: >
            If enabled, tooltip hints will be shown when a signer attempts to sign a document.
          example: false

        setting_signing_questions:
          type: boolean
          description: >
            If enabled, signers can send you questions or comments directly from the signing page.
          example: true

        setting_pdf_audit_trail_hide:
          type: boolean
          description: >
            If enabled, all party email addresses and mobile numbers will be hidden on the signing page and PDF certificate audit trail.
          example: true

        setting_all_at_once_default:
          type: boolean
          description: >
            If enabled, envelopes are sent to all parties simultaneously by default (all-at-once signing).
            If disabled, envelopes are sent to the first party only (one-at-a-time signing).
            Default is `true`.
          example: true

    SettingsResponse:
      allOf:
        - type: object
          properties:
            http:
              type: integer
              example: 200
        - $ref: '#/components/schemas/SettingsFields'

    UpdateSettingsRequest:
      allOf:
        - $ref: '#/components/schemas/SettingsFields'

    UpdateSettingsResponse:
      allOf:
        - type: object
          properties:
            http:
              type: integer
              example: 200
            message:
              type: string
              example: Signable Ltd settings have been updated.
            href:
              type: string
              format: uri
              example: https://api.signable.co.uk/v1/companies/32275
            company_id:
              type: string
              example: "32275"
            company_name:
              type: string
              example: Signable Ltd
        - $ref: '#/components/schemas/SettingsFields'

    WebhookRequest:
      type: object
      required:
        - webhook_url
        - webhook_type
      properties:
        webhook_url:
          type: string
          format: uri
          description: The callback URL where webhook events will be sent.
          example: https://example.com
        webhook_type:
          type: string
          description: >
            The event type to subscribe to. Valid values include:
            `send-envelope`, `signed-envelope`, `cancelled-envelope`, `rejected-envelope`, `bounced-envelope`, 
            `add-user`, `add-contact`, `opened-envelope`, `add-template`, `all`, 
            `signed-envelope-complete`, `verify-envelope-widget`, `signed-envelope-widget`, 
            and `send-envelope-failed`.
          enum:
            - send-envelope
            - signed-envelope
            - cancelled-envelope
            - rejected-envelope
            - bounced-envelope
            - add-user
            - add-contact
            - opened-envelope
            - add-template
            - all
            - signed-envelope-complete
            - verify-envelope-widget
            - signed-envelope-widget
            - send-envelope-failed
          example: send-envelope

    WebhookPostResponse:
      type: object
      required:
        - http
        - message
        - href
        - webhook_id
        - webhook_url
        - webhook_type
        - webhook_created
      properties:
        http:
          type: integer
          description: HTTP status code
          example: 200
        message:
          type: string
          description: Confirmation message about the webhook creation
          example: The webhook (https://example.com) has been created
        href:
          type: string
          format: uri
          description: API resource URL for the newly created webhook
          example: https://api.signable.co.uk/v1/webhooks/152691
        webhook_id:
          type: string
          description: Unique identifier for the created webhook
          example: "152691"
        webhook_url:
          type: string
          format: uri
          description: The callback URL registered for the webhook
          example: https://example.com
        webhook_type:
          type: string
          description: The event type the webhook is subscribed to
          enum:
            - send-envelope
            - signed-envelope
            - cancelled-envelope
            - rejected-envelope
            - bounced-envelope
            - add-user
            - add-contact
            - opened-envelope
            - add-template
            - all
            - signed-envelope-complete
            - verify-envelope-widget
            - signed-envelope-widget
            - send-envelope-failed
          example: all
        webhook_created:
          type: string
          format: date-time
          description: The timestamp when the webhook was created
          example: 2025-06-23T17:15:01+0000
    
    WebhookPutResponse:
      type: object
      required:
        - http
        - message
        - href
        - webhook_id
        - webhook_url
        - webhook_type
        - webhook_updated
      properties:
        http:
          type: integer
          example: 200

        message:
          type: string
          example: The webhook with ID 152691 has been updated

        href:
          type: string
          format: uri
          example: https://api.signable.co.uk/v1/webhooks/152691

        webhook_id:
          type: integer
          example: 152691

        webhook_url:
          type: string
          format: uri
          example: https://andy-example.com

        webhook_type:
          type: string
          enum:
            - send-envelope
            - signed-envelope
            - cancelled-envelope
            - rejected-envelope
            - bounced-envelope
            - add-user
            - add-contact
            - opened-envelope
            - add-template
            - all
            - signed-envelope-complete
            - verify-envelope-widget
            - signed-envelope-widget
            - send-envelope-failed
          example: all

        webhook_updated:
          type: string
          format: date-time
          example: 2025-06-24T09:32:55+0000

    WebhookGetResponse:
      type: object
      required:
        - http
        - webhook_id
        - webhook_url
        - webhook_type
        - webhook_created
        - webhook_updated
        - webhook_suspended
      properties:
        http:
          type: integer
          description: HTTP status code
          example: 200
        webhook_id:
          type: integer
          description: Unique identifier of the webhook
          example: 152691
        webhook_url:
          type: string
          format: uri
          description: The URL to which webhook events are sent
          example: https://example.com
        webhook_type:
          type: string
          description: Type of event the webhook listens for
          enum:
            - send-envelope
            - signed-envelope
            - cancelled-envelope
            - rejected-envelope
            - bounced-envelope
            - add-user
            - add-contact
            - opened-envelope
            - add-template
            - all
            - signed-envelope-complete
            - verify-envelope-widget
            - signed-envelope-widget
            - send-envelope-failed
          example: all
        webhook_created:
          type: string
          format: date-time
          description: Timestamp when the webhook was created
          example: 2025-06-23T17:15:01+0000
        webhook_updated:
          anyOf:
            - type: string
              format: date-time
            - type: "null"
          description: Timestamp when the webhook was last updated
          example: null
        webhook_suspended:
          anyOf:
            - type: boolean
            - type: "null"
          description: Whether the webhook is currently suspended
          example: null

    WebhookListItem:
      type: object
      required:
        - webhook_id
        - webhook_url
        - webhook_type
        - webhook_created
        - webhook_updated
        - webhook_suspended
      properties:
        webhook_id:
          type: string
          description: Unique identifier of the webhook
          example: "132223"

        webhook_url:
          type: string
          format: uri
          description: The URL to which webhook events are sent
          example: https://example.com

        webhook_type:
          type: string
          description: The type of event the webhook listens for
          enum:
            - send-envelope
            - signed-envelope
            - cancelled-envelope
            - rejected-envelope
            - bounced-envelope
            - add-user
            - add-contact
            - opened-envelope
            - add-template
            - all
            - signed-envelope-complete
            - verify-envelope-widget
            - signed-envelope-widget
            - send-envelope-failed
          example: send-envelope

        webhook_created:
          type: string
          format: date-time
          description: Timestamp when the webhook was created
          example: 2025-06-23T17:15:01+0000

        webhook_updated:
          anyOf:
            - type: string
              format: date-time
            - type: "null"
          description: When the webhook was last updated
          example: null

        webhook_suspended:
          anyOf:
            - type: string
              format: date-time
            - type: "null"
          description: When the webhook was suspended (or null if active)
          example: null

    WebhookListResponse:
      type: object
      required:
        - http
        - offset
        - limit
        - total_webhooks
        - webhooks
      properties:
        http:
          type: integer
          example: 200
        offset:
          type: integer
          example: 10
        limit:
          type: integer
          example: 10
        total_webhooks:
          type: string
          example: "44"
        next:
          type: string
          format: uri
          example: https://api.signable.co.uk/v1/webhooks?offset=10&limit=10
        webhooks:
          type: array
          items:
            $ref: '#/components/schemas/WebhookListItem'

    WebhookDeleteResponse:
      type: object
      required:
        - http
        - message
        - webhook_id
        - webhook_url
        - webhook_type
      properties:
        http:
          type: integer
          description: HTTP status code
          example: 200

        message:
          type: string
          description: Descriptive message confirming the webhook was removed
          example: The webhook (https://andy-example.com) has been removed from your account.

        webhook_id:
          type: integer
          description: Unique identifier of the deleted webhook
          example: 152691

        webhook_url:
          type: string
          format: uri
          description: The URL of the deleted webhook
          example: https://andy-example.com

        webhook_type:
          type: string
          description: Type of event the deleted webhook was subscribed to
          enum:
            - send-envelope
            - signed-envelope
            - cancelled-envelope
            - rejected-envelope
            - bounced-envelope
            - add-user
            - add-contact
            - opened-envelope
            - add-template
            - all
            - signed-envelope-complete
            - verify-envelope-widget
            - signed-envelope-widget
            - send-envelope-failed
          example: all

  examples:
    BrandingResponseExample:
      summary: Example branding configuration
      value:
        http: 200
        branding_logo: https://www.signable.co.uk/signable.png
        branding_colour: "#0095E6"

    BrandingPutRequest:
      summary: Example branding update request
      value:
        branding_logo_url: https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png
        branding_colour: "#558caa"

    BrandingPutResponse:
      summary: Branding successfully updated
      value:
        http: 200
        message: Branding options have been updated.
        branding_logo: https://assets.signable.co.uk/company-logo/213690-1751360856.png
        branding_colour: "#558CAA"

    SettingsResponseExample:
      summary: Example company settings response
      value:
        http: 200
        setting_signature_more_info: true
        setting_signature_format_accepted: typed,drawn,upload
        setting_signature_format_default: typed
        setting_email_pdf_attach: true
        setting_email_envelope_open: true
        setting_email_main_email: true
        setting_email_return_address_user: true
        setting_signing_consumer_regulations_act: false
        setting_signing_tooltips: false
        setting_signing_questions: true
        setting_pdf_audit_trail_hide: true
        setting_all_at_once_default: false

    SettingsPutRequestExample:
      summary: Example of an update company settings request payload
      value:
        setting_signature_more_info: true
        setting_signature_format_accepted: typed,drawn,upload
        setting_signature_format_default: typed
        setting_email_pdf_attach: true
        setting_email_envelope_open: true
        setting_email_main_email: true
        setting_email_return_address_user: true
        setting_signing_consumer_regulations_act: false
        setting_signing_tooltips: false
        setting_signing_questions: true
        setting_pdf_audit_trail_hide: true
        setting_all_at_once_default: false

    SettingsPutResponseExample:
      summary: A successful update of company settings
      value:
        http: 200
        message: Signable Ltd settings have been updated.
        href: https://api.signable.co.uk/v1/companies/32275
        company_id: "32275"
        company_name: Signable Ltd
        setting_signature_more_info: true
        setting_signature_format_accepted: typed,drawn,upload
        setting_signature_format_default: typed
        setting_email_pdf_attach: true
        setting_email_envelope_open: true
        setting_email_main_email: true
        setting_email_return_address_user: true
        setting_signing_consumer_regulations_act: false
        setting_signing_tooltips: true
        setting_signing_questions: false
        setting_pdf_audit_trail_hide: true
        setting_all_at_once_default: false

    WebhookRequestExample:
      summary: Example of a webhook request payload
      value:
        webhook_url: https://example.com/webhook
        webhook_type: send-envelope

    WebhookPostResponseExample:
      summary: Example response after creating a webhook
      value:
        http: 200
        message: The webhook (https://example.com) has been created
        href: https://api.signable.co.uk/v1/webhooks/152691
        webhook_id: "152691"
        webhook_url: https://example.com
        webhook_type: all
        webhook_created: 2025-06-23T17:15:01+0000

    WebhookPutResponseExample:
      summary: Example response from updating a webhook
      value:
        http: 200
        message: The webhook with ID 152691 has been updated
        href: https://api.signable.co.uk/v1/webhooks/152691
        webhook_id: 152691
        webhook_url: https://andy-example.com
        webhook_type: all
        webhook_updated: 2025-06-24T09:32:55+0000

    WebhookGetResponseExample:
      summary: Example of a single webhook fetched by ID
      value:
        http: 200
        webhook_id: 152691
        webhook_url: https://example.com
        webhook_type: all
        webhook_created: 2025-06-23T17:15:01+0000
        webhook_updated: null
        webhook_suspended: null

    WebhookListResponseExample:
      summary: Paginated list of webhooks
      value:
        http: 200
        offset: 10
        limit: 10
        total_webhooks: "44"
        next: https://api.signable.co.uk/v1/webhooks?offset=10&limit=10
        webhooks:
          - webhook_id: "132223"
            webhook_url: https://mylovelyendpointfortesting.free.beeceptor.com
            webhook_type: all
            webhook_created: 2019-01-29T18:22:05+0000
            webhook_suspended: 2024-07-11T12:21:12+0000
            webhook_updated: 2024-07-11T12:21:12+0000
          - webhook_id: "133097"
            webhook_url: https://webhook.site/e9f2c61c-98ec-4277-bef8-cf6bca506583
            webhook_type: send-envelope
            webhook_created: 2019-07-29T14:20:40+0000
            webhook_suspended: 2024-07-11T12:10:22+0000
            webhook_updated: 2024-07-11T12:10:22+0000
          - webhook_id: "133203"
            webhook_url: https://webhook.site/1b225ac0-703d-4d91-ab35-751034157ace
            webhook_type: cancelled-envelope
            webhook_created: 2019-08-22T08:38:35+0000
            webhook_suspended: 2024-07-17T08:48:02+0000
            webhook_updated: 2024-07-17T08:48:02+0000

    WebhookDeleteResponseExample:
      summary: Example response after deleting a webhook
      value:
        http: 200
        message: The webhook (https://andy-example.com) has been removed from your account.
        webhook_id: 152691
        webhook_url: https://andy-example.com
        webhook_type: all

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: >
        Authenticate using HTTP Basic Authentication.
        Use your API key as the username and the password can be anything. For ease of use we recommend "x".
